import { describe, expect, it } from "vitest";
import { getSettingsState, resetMswState } from "../test/msw/state";

describe("MSW defaults", () => {
  it("settings defaults stay aligned with Rust backend", () => {
    resetMswState();

    expect(getSettingsState()).toEqual({
      schema_version: 34,
      preferred_port: 37123,
      show_home_heatmap: true,
      show_home_usage: true,
      home_usage_period: "last15",
      gateway_listen_mode: "localhost",
      gateway_custom_listen_address: "",
      wsl_auto_config: false,
      wsl_target_cli: { claude: true, codex: true, gemini: true },
      cli_priority_order: ["claude", "codex", "gemini"],
      wsl_host_address_mode: "auto",
      wsl_custom_host_address: "127.0.0.1",
      codex_home_mode: "user_home_default",
      codex_home_override: "",
      codex_oauth_compatible_proxy_mode: false,
      auto_start: false,
      start_minimized: false,
      tray_enabled: true,
      enable_cli_proxy_startup_recovery: true,
      log_retention_days: 7,
      request_log_retention_days: 0,
      provider_cooldown_seconds: 30,
      provider_base_url_ping_cache_ttl_seconds: 60,
      upstream_first_byte_timeout_seconds: 30,
      upstream_stream_idle_timeout_seconds: 300,
      upstream_request_timeout_non_streaming_seconds: 0,
      update_releases_url: "https://github.com/zsr131550/aio-coding-hub-rust/releases",
      failover_max_attempts_per_provider: 5,
      failover_max_providers_to_try: 5,
      circuit_breaker_failure_threshold: 5,
      circuit_breaker_open_duration_minutes: 30,
      enable_circuit_breaker_notice: false,
      verbose_provider_error: true,
      intercept_anthropic_warmup_requests: true,
      enable_thinking_signature_rectifier: true,
      enable_thinking_budget_rectifier: true,
      enable_billing_header_rectifier: false,
      enable_codex_session_id_completion: true,
      enable_claude_metadata_user_id_injection: true,
      enable_cache_anomaly_monitor: false,
      enable_debug_log: false,
      enable_task_complete_notify: true,
      enable_notification_sound: true,
      enable_response_fixer: true,
      response_fixer_fix_encoding: true,
      response_fixer_fix_sse_format: true,
      response_fixer_fix_truncated_json: true,
      response_fixer_max_json_depth: 200,
      response_fixer_max_fix_size: 1048576,
      cx2cc_fallback_model_opus: "gpt-5.4",
      cx2cc_fallback_model_sonnet: "gpt-5.4",
      cx2cc_fallback_model_haiku: "gpt-5.4",
      cx2cc_fallback_model_main: "gpt-5.4",
      cx2cc_model_reasoning_effort: "",
      cx2cc_service_tier: "",
      cx2cc_disable_response_storage: true,
      cx2cc_enable_reasoning_to_thinking: true,
      cx2cc_drop_stop_sequences: true,
      cx2cc_clean_schema: true,
      cx2cc_filter_batch_tool: true,
      upstream_proxy_enabled: false,
      upstream_proxy_url: "",
      upstream_proxy_username: "",
      upstream_proxy_password_configured: false,
    });
  });
});
